import { Component, OnInit, OnDestroy } from '@angular/core';
import { FormsModule } from '@angular/forms';
import { CommonModule } from '@angular/common'; // Import CommonModule
import { Store, select } from '@ngrx/store';
import { Observable, Subscription } from 'rxjs';
import { map } from 'rxjs/operators';
import { DatePipe } from '@angular/common';
import * as ToDoActions from '../todo.action';
import ToDo from '../todo.model';
import ToDoState from '../todo.state';
declare var bootstrap: any;
@Component({
  selector: 'app-to-do',
  templateUrl: './to-do.component.html',
  styleUrls: ['./to-do.component.scss'],
  standalone: true,
  imports: [FormsModule, CommonModule], // Include CommonModule here
  providers: [DatePipe],
})
export class ToDoComponent implements OnInit, OnDestroy {
  constructor(
    private store: Store<{ todos: ToDoState }>,
    private datePipe: DatePipe
  ) {
    this.todo$ = store.pipe(select('todos'));
  }

  ngOnInit() {
    this.ToDoSubscription = this.todo$
      .pipe(
        map((x) => {
          this.ToDoList = x.ToDos;
          this.todoError = x.ToDoError;
        })
      )
      .subscribe();

    this.store.dispatch(ToDoActions.GetToDoAction());
  }

  todo$: Observable<ToDoState>;
  ToDoSubscription: Subscription;
  ToDoList: ToDo[] = [];
  Title: string = '';
  Description: string = '';
  DueDate: Date = new Date();
  Priority: 'low' | 'medium' | 'high' = 'low';
  Status: 'to-do' | 'in-progress' | 'completed' = 'to-do';
  IsCompleted: boolean = false;

  todoError: Error = null;

  // For editing
  isEditing: boolean = false;
  currentTaskId: string = '';
  selectedTask: ToDo | null = null;

  createToDo() {
    if (this.isEditing) {
      this.updateToDo();
      return;
    }

    const todo: ToDo = {
      _id: '',
      title: this.Title,
      description: this.Description,
      dueDate: this.DueDate,
      priority: this.Priority,
      status: this.Status,
      isCompleted: this.IsCompleted,
      id: '', // Assuming id will be generated by the backend
    };
    this.store.dispatch(ToDoActions.CreateToDoAction({ payload: todo }));
    this.resetForm();
    this.closeModal();
  }

  editToDo(todo: ToDo) {
    this.isEditing = true;
    this.currentTaskId = todo._id;
    this.Title = todo.title;
    this.Description = todo.description;
    this.DueDate = new Date(todo.dueDate);
    this.Priority = todo.priority;
    this.Status = todo.status;
    this.IsCompleted = todo.isCompleted;
    // Open the modal
    const modal = new bootstrap.Modal(document.getElementById('editTaskModal'));
    modal.show();
  }

  updateToDo() {
    const updatedTodo: ToDo = {
      _id: this.currentTaskId,
      title: this.Title,
      description: this.Description,
      dueDate: this.DueDate,
      priority: this.Priority,
      status: this.Status,
      isCompleted: this.IsCompleted,
      id: this.currentTaskId,
    };
    this.store.dispatch(ToDoActions.UpdateToDoAction({ payload: updatedTodo }));
    this.isEditing = false;
    this.currentTaskId = '';
    this.resetForm();
    this.closeModal();
  }

  deleteToDo(id: string) {
    this.store.dispatch(ToDoActions.DeleteToDoAction({ id }));
  }

  resetForm() {
    this.Title = '';
    this.Description = '';
    this.DueDate = new Date();
    this.Priority = 'low';
    this.Status = 'to-do';
    this.IsCompleted = false;
    this.isEditing = false;
    this.currentTaskId = '';
  }

  ngOnDestroy() {
    if (this.ToDoSubscription) {
      this.ToDoSubscription.unsubscribe();
    }
  }

  formatDate(date: Date): string {
    return this.datePipe.transform(date, 'shortDate') || '';
  }

  closeModal() {
    const modal = new bootstrap.Modal(document.getElementById('editTaskModal'));
    this.resetForm();
    modal.hide();
  }
  showHistory(id: string) {
    this.store.dispatch(ToDoActions.GetHistoryAction({ id }));
    const modal = new bootstrap.Modal(document.getElementById('historyModal'));
    modal.show();
  }
  closeHistory() {
    const modal = new bootstrap.Modal(document.getElementById('historyModal'));
    modal.hide();
  }
}
